---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "identity-claim-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "identity-claim-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "identity-claim-operator.managerClusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "identity-claim-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.metrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "identity-claim-operator.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "identity-claim-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "identity-claim-operator.metricsAuthClusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "identity-claim-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
