{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "identity-claim-operator.fullname" . }}-allow-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "identity-claim-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "identity-claim-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.metrics.port }}
{{- end }}
